# Generated by Django 5.0.6 on 2024-05-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('amount_compressor', models.PositiveSmallIntegerField()),
                ('no_frost', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.category')),
            ],
            options={
                'verbose_name': 'Refrigerator',
                'verbose_name_plural': 'Refrigerators',
                'ordering': ['name', 'amount_compressor', 'no_frost', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Compressor model')),
                ('refrigerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.refrigerator')),
            ],
            options={
                'verbose_name': 'Compressor',
                'verbose_name_plural': 'Compressors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(blank=True, help_text='Additional info, result of research', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('in_process', 'In Process')], max_length=50)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.refrigerator')),
            ],
            options={
                'verbose_name': 'Refrigerator research',
                'verbose_name_plural': 'Refrigerator research',
                'ordering': ['device', 'status', 'date_start', 'date_finish'],
            },
        ),
    ]
